# Set up mitiemann home directory and SSH key on first boot
d /var/home/mitiemann      0700 mitiemann mitiemann -
d /var/home/mitiemann/.ssh 0700 mitiemann mitiemann -
C /var/home/mitiemann/.ssh/authorized_keys 0600 mitiemann mitiemann - /etc/ssh/authorized_keys.d/mitiemann
